# Generated by Django 5.2 on 2025-12-31 11:57

import apps.data_aggregation.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Source Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aggregation Source',
                'verbose_name_plural': 'Aggregation Sources',
                'db_table': 'aggregation_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Credit card number (unique identifier)', max_length=19, unique=True, verbose_name='卡号')),
                ('expiry_month', models.IntegerField(help_text='Card expiry month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='有效期月份')),
                ('expiry_year', models.IntegerField(help_text='Card expiry year (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2000)], verbose_name='有效期年份')),
                ('passkey', models.CharField(help_text='Passkey for credit card authentication', max_length=128, verbose_name='Passkey')),
                ('last_balance_update', models.DateTimeField(blank=True, help_text='Last time the balance was updated', null=True, verbose_name='最近更新余额时间')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Credit card limit amount', max_digits=12, verbose_name='额度')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'db_table': 'credit_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Debit card number (unique identifier)', max_length=19, unique=True, verbose_name='卡号')),
                ('expiry_month', models.IntegerField(help_text='Card expiry month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='有效期月份')),
                ('expiry_year', models.IntegerField(help_text='Card expiry year (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2000)], verbose_name='有效期年份')),
                ('passkey', models.CharField(help_text='Passkey for debit card authentication', max_length=128, verbose_name='Passkey')),
                ('last_balance_update', models.DateTimeField(blank=True, help_text='Last time the balance was updated', null=True, verbose_name='最近更新余额时间')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Debit card balance amount', max_digits=12, verbose_name='余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Debit Card',
                'verbose_name_plural': 'Debit Cards',
                'db_table': 'debit_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AggregationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Celery Task ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Task Result')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='data_aggregation.aggregationsource')),
            ],
            options={
                'verbose_name': 'Aggregation Task',
                'verbose_name_plural': 'Aggregation Tasks',
                'db_table': 'aggregation_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('reservation_time', models.DateTimeField(blank=True, null=True)),
                ('visit_time', models.DateTimeField(blank=True, null=True)),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('info_updated_at', models.DateTimeField(auto_now=True)),
                ('order_detail_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EC Site',
                'verbose_name_plural': 'EC Sites',
                'db_table': 'ec_site',
                'ordering': ['-order_created_at'],
                'indexes': [models.Index(fields=['reservation_number'], name='ec_site_reserva_d404b0_idx'), models.Index(fields=['order_created_at'], name='ec_site_order_c_acf061_idx'), models.Index(fields=['visit_time'], name='ec_site_visit_t_92dcdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='iPad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Unique part number (e.g., MG674J/A)', max_length=50, unique=True, verbose_name='Part Number')),
                ('model_name', models.CharField(help_text='Product model name', max_length=100, verbose_name='Model Name')),
                ('color', models.CharField(help_text='Device color', max_length=50, verbose_name='Color')),
                ('release_date', models.DateField(help_text='Official release date', verbose_name='Release Date')),
                ('jan', models.CharField(help_text='Japanese Article Number (13 digits)', max_length=13, unique=True, verbose_name='JAN Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_gb', models.IntegerField(help_text='Storage capacity in GB', verbose_name='Capacity (GB)')),
            ],
            options={
                'verbose_name': 'iPad',
                'verbose_name_plural': 'iPads',
                'db_table': 'ipads',
                'ordering': ['-release_date', 'model_name'],
                'indexes': [models.Index(fields=['model_name'], name='ipads_model_n_53e4d0_idx'), models.Index(fields=['release_date'], name='ipads_release_5f3703_idx'), models.Index(fields=['jan'], name='ipads_jan_662c06_idx'), models.Index(fields=['part_number'], name='ipads_part_nu_512e61_idx')],
            },
        ),
        migrations.CreateModel(
            name='iPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Unique part number (e.g., MG674J/A)', max_length=50, unique=True, verbose_name='Part Number')),
                ('model_name', models.CharField(help_text='Product model name', max_length=100, verbose_name='Model Name')),
                ('color', models.CharField(help_text='Device color', max_length=50, verbose_name='Color')),
                ('release_date', models.DateField(help_text='Official release date', verbose_name='Release Date')),
                ('jan', models.CharField(help_text='Japanese Article Number (13 digits)', max_length=13, unique=True, verbose_name='JAN Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_gb', models.IntegerField(help_text='Storage capacity in GB', verbose_name='Capacity (GB)')),
            ],
            options={
                'verbose_name': 'iPhone',
                'verbose_name_plural': 'iPhones',
                'db_table': 'iphones',
                'ordering': ['-release_date', 'model_name'],
                'indexes': [models.Index(fields=['model_name'], name='iphones_model_n_46ddab_idx'), models.Index(fields=['release_date'], name='iphones_release_381f18_idx'), models.Index(fields=['jan'], name='iphones_jan_33bc93_idx'), models.Index(fields=['part_number'], name='iphones_part_nu_fa2bbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalPersonOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, unique=True, verbose_name='UUID')),
                ('username', models.CharField(help_text='Customer username', max_length=50, verbose_name='Username')),
                ('appointment_time', models.DateTimeField(blank=True, help_text='Scheduled appointment time at store', null=True, verbose_name='Appointment Time')),
                ('visit_time', models.DateTimeField(blank=True, help_text='Actual visit time to store', null=True, verbose_name='Visit Time')),
                ('order_created_at', models.DateTimeField(auto_now_add=True, help_text='Order creation time', verbose_name='Order Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Legal Person Offline',
                'verbose_name_plural': 'Legal Person Offline',
                'db_table': 'legal_person_offline',
                'ordering': ['-order_created_at'],
                'indexes': [models.Index(fields=['uuid'], name='legal_perso_uuid_795dee_idx'), models.Index(fields=['username'], name='legal_perso_usernam_fb3dc2_idx'), models.Index(fields=['-order_created_at'], name='legal_perso_order_c_4ee359_idx'), models.Index(fields=['visit_time'], name='legal_perso_visit_t_e1c7be_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfficialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, unique=True, verbose_name='UUID')),
                ('account_id', models.CharField(help_text='Account ID (may not be unique)', max_length=50, verbose_name='账号ID')),
                ('email', models.CharField(help_text='Email address (must be unique)', max_length=50, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(help_text='Account holder name', max_length=50, verbose_name='姓名')),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=50, verbose_name='邮编')),
                ('address_line_1', models.CharField(blank=True, help_text='Address line 1', max_length=50, verbose_name='地址1')),
                ('address_line_2', models.CharField(blank=True, help_text='Address line 2', max_length=50, verbose_name='地址2')),
                ('address_line_3', models.CharField(blank=True, help_text='Address line 3', max_length=50, verbose_name='地址3')),
                ('passkey', models.CharField(help_text='Account passkey', max_length=50, verbose_name='Passkey')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Official Account',
                'verbose_name_plural': 'Official Accounts',
                'db_table': 'official_accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uuid'], name='official_ac_uuid_a9f1e9_idx'), models.Index(fields=['email'], name='official_ac_email_0b2c8b_idx'), models.Index(fields=['account_id'], name='official_ac_account_229f72_idx'), models.Index(fields=['-created_at'], name='official_ac_created_a1ef86_idx')],
            },
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, unique=True, verbose_name='UUID')),
                ('order_number', models.CharField(help_text='Purchase order number', max_length=50, unique=True, verbose_name='订单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Order creation time', verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Order confirmation time', null=True, verbose_name='认可时间')),
                ('shipped_at', models.DateTimeField(blank=True, help_text='Shipment time', null=True, verbose_name='发送时间')),
                ('estimated_website_arrival_date', models.DateField(blank=True, help_text='Estimated arrival date from website', null=True, verbose_name='官网到达预计时间')),
                ('tracking_number', models.CharField(blank=True, help_text='Shipping tracking number', max_length=50, verbose_name='邮寄单号')),
                ('estimated_delivery_date', models.DateField(blank=True, help_text='Estimated delivery date', null=True, verbose_name='邮寄送达预计时间')),
                ('delivery_status', models.CharField(choices=[('pending_confirmation', '等待确认'), ('shipped', '已发送'), ('in_delivery', '配送中'), ('delivered', '已送达')], default='pending_confirmation', help_text='Delivery status', max_length=30, verbose_name='送达状态')),
                ('last_info_updated_at', models.DateTimeField(blank=True, help_text='Last information update time', null=True, verbose_name='最后信息更新时间')),
                ('account_used', models.CharField(blank=True, help_text='Account used for purchase', max_length=50, verbose_name='使用账号')),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', '信用卡'), ('gift_card', '礼品卡'), ('card', '卡片'), ('backup', '备用')], help_text='Payment method used', max_length=20, verbose_name='使用付款方式')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('official_account', models.ForeignKey(blank=True, help_text='Official account associated with this purchasing order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_orders', to='data_aggregation.officialaccount', verbose_name='Official Account')),
            ],
            options={
                'verbose_name': 'Purchasing Order',
                'verbose_name_plural': 'Purchasing Orders',
                'db_table': 'purchasing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Gift card number (unique identifier)', max_length=50, unique=True, verbose_name='卡号')),
                ('passkey1', models.CharField(help_text='First passkey for gift card authentication', max_length=50, verbose_name='Passkey 1')),
                ('passkey2', models.CharField(help_text='Second passkey for gift card authentication', max_length=50, verbose_name='Passkey 2')),
                ('balance', models.IntegerField(help_text='Gift card balance amount', verbose_name='余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('purchasings', models.ManyToManyField(blank=True, help_text='Purchasing orders associated with this gift card', related_name='gift_cards', to='data_aggregation.purchasing', verbose_name='Purchasing Orders')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'db_table': 'gift_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Amount paid with this debit card', max_digits=12, verbose_name='支付金额')),
                ('payment_time', models.DateTimeField(auto_now_add=True, help_text='Time when the payment was made', verbose_name='支付时间')),
                ('payment_status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败'), ('refunded', '已退款')], default='pending', help_text='Status of the payment', max_length=20, verbose_name='支付状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('debit_card', models.ForeignKey(help_text='Debit card used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='data_aggregation.debitcard', verbose_name='Debit Card')),
                ('purchasing', models.ForeignKey(help_text='Purchasing order for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_card_payments', to='data_aggregation.purchasing', verbose_name='Purchasing Order')),
            ],
            options={
                'verbose_name': 'Debit Card Payment',
                'verbose_name_plural': 'Debit Card Payments',
                'db_table': 'debit_card_payments',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.AddField(
            model_name='debitcard',
            name='purchasings',
            field=models.ManyToManyField(blank=True, help_text='Purchasing orders associated with this debit card', related_name='debit_cards', through='data_aggregation.DebitCardPayment', to='data_aggregation.purchasing', verbose_name='Purchasing Orders'),
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Amount paid with this credit card', max_digits=12, verbose_name='支付金额')),
                ('payment_time', models.DateTimeField(auto_now_add=True, help_text='Time when the payment was made', verbose_name='支付时间')),
                ('payment_status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败'), ('refunded', '已退款')], default='pending', help_text='Status of the payment', max_length=20, verbose_name='支付状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('credit_card', models.ForeignKey(help_text='Credit card used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='data_aggregation.creditcard', verbose_name='Credit Card')),
                ('purchasing', models.ForeignKey(help_text='Purchasing order for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_payments', to='data_aggregation.purchasing', verbose_name='Purchasing Order')),
            ],
            options={
                'verbose_name': 'Credit Card Payment',
                'verbose_name_plural': 'Credit Card Payments',
                'db_table': 'credit_card_payments',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.AddField(
            model_name='creditcard',
            name='purchasings',
            field=models.ManyToManyField(blank=True, help_text='Purchasing orders associated with this credit card', related_name='credit_cards', through='data_aggregation.CreditCardPayment', to='data_aggregation.purchasing', verbose_name='Purchasing Orders'),
        ),
        migrations.CreateModel(
            name='TemporaryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Record creation time', verbose_name='创建时间')),
                ('expected_time', models.DateTimeField(help_text='Expected arrival time', verbose_name='入库预计时间')),
                ('record', models.CharField(help_text='Record information', max_length=255, verbose_name='记录')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update time', verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': 'Temporary Channel',
                'verbose_name_plural': 'Temporary Channels',
                'db_table': 'temporary_channels',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['-created_time'], name='temporary_c_created_0f6f2a_idx'), models.Index(fields=['expected_time'], name='temporary_c_expecte_40b777_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, unique=True, verbose_name='UUID')),
                ('flag', models.CharField(blank=True, help_text='Human-readable identifier (rules to be implemented)', max_length=100, verbose_name='Flag')),
                ('transaction_confirmed_at', models.DateTimeField(blank=True, help_text='Time when transaction was confirmed', null=True, verbose_name='Transaction Confirmed At')),
                ('scheduled_arrival_at', models.DateTimeField(blank=True, help_text='Scheduled arrival time', null=True, verbose_name='Scheduled Arrival At')),
                ('checked_arrival_at_1', models.DateTimeField(blank=True, help_text='First checked arrival time', null=True, verbose_name='Checked Arrival Time 1')),
                ('checked_arrival_at_2', models.DateTimeField(blank=True, help_text='Second checked arrival time', null=True, verbose_name='Checked Arrival Time 2')),
                ('actual_arrival_at', models.DateTimeField(blank=True, help_text='Actual arrival time', null=True, verbose_name='Actual Arrival At')),
                ('status', models.CharField(choices=[('in_transit', '到达中'), ('arrived', '到达'), ('out_of_stock', '出库'), ('abnormal', '异常')], default='in_transit', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('source1', models.ForeignKey(blank=True, help_text='Purchase source 1 - EC Site', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecsite_inventories', to='data_aggregation.ecsite', verbose_name='Source 1 (EC Site)')),
                ('ipad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipad_inventories', to='data_aggregation.ipad', verbose_name='iPad Product')),
                ('iphone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iphone_inventories', to='data_aggregation.iphone', verbose_name='iPhone Product')),
                ('source3', models.ForeignKey(blank=True, help_text='Legal person offline purchase source', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_person_inventories', to='data_aggregation.legalpersonoffline', verbose_name='Source 3 - Legal Person Offline')),
                ('source2', models.ForeignKey(blank=True, help_text='Purchasing order associated with this inventory item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_inventories', to='data_aggregation.purchasing', verbose_name='Source 2 (Purchasing)')),
                ('source4', models.ForeignKey(blank=True, help_text='Temporary channel purchase source', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_channel_inventories', to='data_aggregation.temporarychannel', verbose_name='Source 4 - Temporary Channel')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AggregatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Aggregated Data')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('aggregated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_data', to='data_aggregation.aggregationsource')),
            ],
            options={
                'verbose_name': 'Aggregated Data',
                'verbose_name_plural': 'Aggregated Data',
                'db_table': 'aggregated_data',
                'ordering': ['-aggregated_at'],
                'indexes': [models.Index(fields=['-aggregated_at'], name='aggregated__aggrega_ed3472_idx'), models.Index(fields=['source', '-aggregated_at'], name='aggregated__source__ca8f75_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchasing',
            index=models.Index(fields=['uuid'], name='purchasing_uuid_9c752a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasing',
            index=models.Index(fields=['order_number'], name='purchasing_order_n_fbe0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasing',
            index=models.Index(fields=['delivery_status'], name='purchasing_deliver_7e6252_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasing',
            index=models.Index(fields=['created_at'], name='purchasing_created_913dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasing',
            index=models.Index(fields=['-shipped_at'], name='purchasing_shipped_f30dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasing',
            index=models.Index(fields=['tracking_number'], name='purchasing_trackin_d01a54_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['card_number'], name='gift_cards_card_nu_006d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['-created_at'], name='gift_cards_created_b4b35e_idx'),
        ),
        migrations.AddIndex(
            model_name='debitcardpayment',
            index=models.Index(fields=['payment_status'], name='debit_card__payment_0a523a_idx'),
        ),
        migrations.AddIndex(
            model_name='debitcardpayment',
            index=models.Index(fields=['-payment_time'], name='debit_card__payment_94a791_idx'),
        ),
        migrations.AddIndex(
            model_name='debitcard',
            index=models.Index(fields=['card_number'], name='debit_cards_card_nu_3efb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='debitcard',
            index=models.Index(fields=['-created_at'], name='debit_cards_created_ef4ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='debitcard',
            index=models.Index(fields=['last_balance_update'], name='debit_cards_last_ba_35ee8f_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardpayment',
            index=models.Index(fields=['payment_status'], name='credit_card_payment_01e271_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardpayment',
            index=models.Index(fields=['-payment_time'], name='credit_card_payment_f9f6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['card_number'], name='credit_card_card_nu_055321_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['-created_at'], name='credit_card_created_bd7f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['last_balance_update'], name='credit_card_last_ba_2d393d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['uuid'], name='inventory_uuid_05737c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['status'], name='inventory_status_2fc879_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['created_at'], name='inventory_created_efb683_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['-actual_arrival_at'], name='inventory_actual__bb3778_idx'),
        ),
    ]
