# Generated by Django 5.2 on 2026-01-20 12:11

import apps.data_aggregation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregation', '0020_add_delivery_status_query_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, unique=True, verbose_name='UUID')),
                ('first_record_uuid', models.CharField(help_text='UUID of the existing record (LegalPersonOffline/TemporaryChannel/Purchasing/EcSite)', max_length=59, verbose_name='First Record UUID')),
                ('second_record_uuid', models.CharField(help_text='UUID of the new record (LegalPersonOffline/TemporaryChannel/Purchasing/EcSite)', max_length=59, verbose_name='Second Record UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Duplicate Product',
                'verbose_name_plural': 'Duplicate Products',
                'db_table': 'duplicate_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='mailattachment',
            new_name='data_aggreg_message_d62b9a_idx',
            old_name='data_aggreg_message_7b1e24_idx',
        ),
        migrations.RenameIndex(
            model_name='mailattachment',
            new_name='data_aggreg_mime_ty_9545f3_idx',
            old_name='data_aggreg_mime_ty_d1c0c7_idx',
        ),
        migrations.RenameIndex(
            model_name='mailattachment',
            new_name='data_aggreg_sha256_cffe69_idx',
            old_name='data_aggreg_sha256_fb9ff5_idx',
        ),
        migrations.RenameIndex(
            model_name='maillabel',
            new_name='data_aggreg_account_c375d7_idx',
            old_name='data_aggreg_account_e15ee9_idx',
        ),
        migrations.RenameIndex(
            model_name='maillabel',
            new_name='data_aggreg_account_88a652_idx',
            old_name='data_aggreg_account_2cc41f_idx',
        ),
        migrations.RenameIndex(
            model_name='mailmessage',
            new_name='data_aggreg_account_ae8a95_idx',
            old_name='data_aggreg_account_22f6bb_idx',
        ),
        migrations.RenameIndex(
            model_name='mailmessage',
            new_name='data_aggreg_account_ad65a4_idx',
            old_name='data_aggreg_account_3cb72e_idx',
        ),
        migrations.RenameIndex(
            model_name='mailmessage',
            new_name='data_aggreg_account_d5f46b_idx',
            old_name='data_aggreg_account_1bc6db_idx',
        ),
        migrations.RenameIndex(
            model_name='mailmessage',
            new_name='data_aggreg_account_bb21cc_idx',
            old_name='data_aggreg_account_c4ce7f_idx',
        ),
        migrations.RenameIndex(
            model_name='mailmessage',
            new_name='data_aggreg_account_c51fc0_idx',
            old_name='data_aggreg_account_e3a825_idx',
        ),
        migrations.RenameIndex(
            model_name='mailmessagelabel',
            new_name='data_aggreg_label_i_1f96a6_idx',
            old_name='data_aggreg_label_i_da5c5e_idx',
        ),
        migrations.RenameIndex(
            model_name='mailmessagelabel',
            new_name='data_aggreg_message_e3309c_idx',
            old_name='data_aggreg_message_56a79c_idx',
        ),
        migrations.RenameIndex(
            model_name='mailthread',
            new_name='data_aggreg_account_b11be0_idx',
            old_name='data_aggreg_account_01f748_idx',
        ),
        migrations.RenameIndex(
            model_name='orderconflict',
            new_name='order_confl_uuid_e633d0_idx',
            old_name='order_confl_uuid_8d71d1_idx',
        ),
        migrations.RenameIndex(
            model_name='orderconflict',
            new_name='order_confl_is_proc_82ecac_idx',
            old_name='order_confl_is_proc_5e4c3a_idx',
        ),
        migrations.RenameIndex(
            model_name='orderconflict',
            new_name='order_confl_created_866e52_idx',
            old_name='order_confl_created_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='orderconflictfield',
            new_name='order_confl_uuid_4b5437_idx',
            old_name='order_confl_uuid_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='orderconflictfield',
            new_name='order_confl_field_n_c5d2d2_idx',
            old_name='order_confl_field_n_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='orderconflictfield',
            new_name='order_confl_is_proc_317dc2_idx',
            old_name='order_confl_is_proc_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='orderconflictfield',
            new_name='order_confl_detecte_9803a4_idx',
            old_name='order_confl_detecte_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasing',
            new_name='purchasing_batch_e_2eb469_idx',
            old_name='purchasing_batch_e_8a1b2c_idx',
        ),
        migrations.AddField(
            model_name='ecsite',
            name='uuid',
            field=models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='historicalecsite',
            name='uuid',
            field=models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='historicallegalpersonoffline',
            name='creation_source',
            field=models.CharField(blank=True, help_text='Source of order creation (e.g., API, manual import, auto sync)', max_length=200, null=True, verbose_name='创建来源'),
        ),
        migrations.AddField(
            model_name='historicaltemporarychannel',
            name='uuid',
            field=models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='legalpersonoffline',
            name='creation_source',
            field=models.CharField(blank=True, help_text='Source of order creation (e.g., API, manual import, auto sync)', max_length=200, null=True, verbose_name='创建来源'),
        ),
        migrations.AddField(
            model_name='temporarychannel',
            name='uuid',
            field=models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='imei',
            field=models.CharField(blank=True, help_text='International Mobile Equipment Identity (up to 17 characters)', max_length=17, null=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='historicalofficialaccount',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Account holder name', max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='imei',
            field=models.CharField(blank=True, help_text='International Mobile Equipment Identity (up to 17 characters)', max_length=17, null=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duplicateproduct',
            name='inventory',
            field=models.ForeignKey(help_text='The newly created inventory item with duplicate IMEI', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_records', to='data_aggregation.inventory', verbose_name='Inventory'),
        ),
    ]
