# Generated by Django 5.2 on 2026-01-20 12:11

import apps.data_aggregation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregation', '0022_fix_uuid_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecsite',
            name='uuid',
            field=models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='historicalecsite',
            name='uuid',
            field=models.CharField(db_index=True, default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='historicaltemporarychannel',
            name='uuid',
            field=models.CharField(db_index=True, default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='temporarychannel',
            name='uuid',
            field=models.CharField(default=apps.data_aggregation.models.generate_uuid, help_text='48-character globally unique identifier', max_length=59, unique=True, verbose_name='UUID'),
        ),
    ]
