# Generated by Django 5.2.6 on 2025-10-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasingShopTimeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_ID', models.UUIDField(blank=True, db_index=True, editable=False, help_text='一次导入/任务的批次标识（uuid4）', null=True, verbose_name='批次ID')),
                ('Job_ID', models.CharField(editable=False, max_length=255, verbose_name='Job_ID')),
                ('Original_Record_Time_Zone', models.CharField(max_length=10, verbose_name='原始记录时区')),
                ('Timestamp_Time_Zone', models.CharField(max_length=10, verbose_name='时间戳时区')),
                ('Record_Time', models.DateTimeField(verbose_name='时间戳时间')),
                ('Timestamp_Time', models.DateTimeField(db_index=True, verbose_name='记录时间')),
                ('Alignment_Time_Difference', models.IntegerField(verbose_name='对齐时间差（s）')),
                ('Update_Count', models.IntegerField(default=0, verbose_name='更新次数')),
                ('New_Product_Price', models.PositiveIntegerField(verbose_name='新品卖取价格(円)')),
                ('Price_A', models.PositiveIntegerField(blank=True, null=True, verbose_name='A品卖取价格(円)')),
                ('Price_B', models.PositiveIntegerField(blank=True, null=True, verbose_name='B品卖取价格(円)')),
                ('Warehouse_Receipt_Time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('iphone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_time_analysis', to='AppleStockChecker.iphone', verbose_name='iPhone')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_time_analysis', to='AppleStockChecker.secondhandshop', verbose_name='二手店')),
            ],
            options={
                'verbose_name': '二手店回收价格记录对齐表',
                'verbose_name_plural': '二手店回收价格记录对齐表',
                'ordering': ['-Timestamp_Time'],
                'indexes': [models.Index(fields=['shop', 'iphone', '-Timestamp_Time'], name='idx_psta_shop_phone_time'), models.Index(fields=['iphone', '-Timestamp_Time'], name='idx_psta_phone_time'), models.Index(fields=['shop', '-Timestamp_Time'], name='idx_psta_shop_time')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'iphone', 'Timestamp_Time'), name='uniq_shop_iphone_Timestamp_Time')],
            },
        ),
    ]
