# Generated by Django 5.2.6 on 2025-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0002_purchasingshoptimeanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Record_Time',
            field=models.DateTimeField(verbose_name='原始记录时间'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Timestamp_Time',
            field=models.DateTimeField(db_index=True, verbose_name='时间戳时间'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Warehouse_Receipt_Time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='落库时间'),
        ),
    ]
