# Generated by Django 5.2.6 on 2025-11-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0009_cohort_display_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopweightprofile',
            name='display_index',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
