# Generated by Django 5.2.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0013_dataingestionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastsnapshot',
            name='iphone',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='AppleStockChecker.iphone',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='forecastsnapshot',
            unique_together={('bucket', 'model_name', 'version', 'horizon_min', 'iphone')},
        ),
    ]
