"""
Django settings for YamagotiProjects project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-3(&zari4^u-6iv$+z_2r2(oviwyj5g#cy*3c$t#x_=-w7cijv1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.app",
    ".ngrok-free.dev",
    "verbless-sadistically-jayceon.ngrok-free.dev",
    "analysis.yamaguchi.lan",
]

# Application definition

INSTALLED_APPS = [
    "channels",
    'simplepro',
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AppleStockChecker.apps.ApplestockcheckerConfig',
    'inbound_goods.apps.InboundGoodsConfig',
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    # 'easyaudit',
    "django_celery_beat",  # 定时任务(可在Admin里改间隔/暂停)
    "django_celery_results",  # 可选：任务结果持久化到DB
    "django_filters",

]

MIDDLEWARE = [
    'elasticapm.contrib.django.middleware.TracingMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # 可选
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
    'simplepro.middlewares.SimpleMiddleware'
]

ROOT_URLCONF = 'YamagotiProjects.urls'

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

try:
    if DEBUG:  # noqa: F821
        REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
            "rest_framework.renderers.BrowsableAPIRenderer"
        )
except NameError:
    pass

# ---- SimpleJWT ----
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # 如需与环境变量 SECRET_KEY 分离，可自定义 SIGNING_KEY
    # "SIGNING_KEY": os.getenv("JWT_SECRET", SECRET_KEY),
}

# ---- OpenAPI 文档 ----
SPECTACULAR_SETTINGS = {
    "TITLE": "Project API",
    "DESCRIPTION": "Django REST Framework + JWT",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"BearerAuth": []}],  # 文档右上角 Authorize 会显示 BearerAuth
    "COMPONENT_SPLIT_REQUEST": True,
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://verbless-sadistically-jayceon.ngrok-free.dev",
    "https://analysis.yamaguchi.lan",
]

# 若你在本地调试 CSRF：
CSRF_TRUSTED_ORIGINS = ["http://localhost:3000",
                        "http://127.0.0.1:3000",
                        "http://127.0.0.1:8000",
                        "https://verbless-sadistically-jayceon.ngrok-free.dev",
                        "https://analysis.yamaguchi.lan",
                        ]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WHITENOISE_MAX_AGE = 60 * 60 * 24 * 7
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

WSGI_APPLICATION = 'YamagotiProjects.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库配置：支持环境变量和 PgBouncer
USE_PGBOUNCER = os.getenv("USE_PGBOUNCER", "false").lower() == "true"

if USE_PGBOUNCER:
    # 通过 PgBouncer 连接（生产环境推荐）
    # PgBouncer 使用事务池模式，连接配置需要特殊处理
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("PGBOUNCER_DATABASE", "applestockchecker_dev"),
            "USER": os.getenv("PGBOUNCER_USER", "samuelzhu"),
            "PASSWORD": os.getenv("PGBOUNCER_PASSWORD", ""),
            "HOST": os.getenv("PGBOUNCER_HOST", "127.0.0.1"),
            "PORT": os.getenv("PGBOUNCER_PORT", "6432"),
            # PgBouncer 事务池模式下，CONN_MAX_AGE 必须为 0
            # 因为 PgBouncer 会在每个事务结束后回收连接
            "CONN_MAX_AGE": 0,
            "CONN_HEALTH_CHECKS": True,  # Django 4.1+ 健康检查
            "OPTIONS": {},
            "DISABLE_SERVER_SIDE_CURSORS": True,  # 关键：PgBouncer 必须禁用
        }
    }
else:
    # 直接连接 PostgreSQL（开发环境）
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DATABASE", "applestockchecker_dev"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "localpass"),
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.getenv("POSTGRES_PORT", "5433"),
            "CONN_MAX_AGE": 0,  # 立即释放连接
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                "options": "-c statement_timeout=60000",
            },
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja-jp'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # collectstatic 产物目录（生产/统一对外）
STATICFILES_DIRS = [
    BASE_DIR / "static",  # 你自己的前端静态目录（可选）
]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",  # 从各 app 的 /static/ 里找（第三方主题用这个）
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

_ws_token = os.getenv("WEB_SCRAPER_API_TOKEN", "")

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# 优先级：settings > 环境变量 > 项目内默认文件
EXTERNAL_IPHONE17_INFO_PATH = BASE_DIR / "AppleStockChecker" / "data" / "iphone17_info.csv"

# WebScraper Cloud API 访问令牌
WEB_SCRAPER_API_TOKEN = _ws_token

# 导出地址模板（如官方变更，可在这里改）
# WEB_SCRAPER_EXPORT_URL_TEMPLATE = "https://api.webscraper.io/api/v1/scraping-job/{job_id}/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"
WEB_SCRAPER_EXPORT_URL_TEMPLATE = "https://api.webscraper.io/api/v1/scraping-job/{job_id}/csv"

# Webhook 共享密钥
WEB_SCRAPER_WEBHOOK_TOKEN = os.getenv("WEB_SCRAPER_WEBHOOK_TOKEN", "")

# 可选：把 WebScraper 的 sitemap 名 或 job 上的 custom_id 映射为清洗器名（shop3/shop4…）
WEB_SCRAPER_SOURCE_MAP = {
    "shop1": "shop1",
    "shop2": "shop2",
    "shop3": "shop3",
    "shop4": "shop4",
    "shop5-1": "shop5-1",
    "shop5-2": "shop5-2",
    "shop5-3": "shop5-3",
    "shop5-4": "shop5-4",
    "shop6-1": "shop6-1",
    "shop6-2": "shop6-2",
    "shop6-3": "shop6-3",
    "shop6-4": "shop6-4",
    "shop7": "shop7",
    "shop8": "shop8",
    "shop9": "shop9",
    "shop10": "shop10",
    "shop11": "shop11",
    "shop12": "shop12",
    "shop13": "shop13",
    "shop14": "shop14",
    "shop15": "shop15",
    "shop16": "shop16",
    "shop17": "shop17",
    "shop18": "shop18",
    "shop19": "shop19",
    "shop20": "shop20",
}

# WEB_SCRAPER_WEBHOOK_TOKEN 已在上方通过 os.getenv 读取

# Celery/Redis
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_TIME_LIMIT = 600
CELERY_TASK_SOFT_TIME_LIMIT = 540
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Tokyo"
CELERY_ENABLE_UTC = False
CELERY_TASK_ACKS_LATE = True  # 任务跑完才确认，异常能重派
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # WorkerLost 也回到队列
CELERY_TASK_TRACK_STARTED = True

# Celery 任务路由配置
CELERY_TASK_ROUTES = {
    # PSTA 任务路由（v3新增）
    "AppleStockChecker.tasks.psta_finalize_buckets": {"queue": "psta_finalize"},
    "AppleStockChecker.tasks.psta_aggregate_features": {"queue": "psta_aggregation"},
    # WebScraper 任务路由
    "AppleStockChecker.tasks.task_process_xlsx": {"queue": "webscraper"},
    "AppleStockChecker.tasks.webscraper_tasks.task_process_webscraper_job": {"queue": "webscraper"},
    "AppleStockChecker.tasks.webscraper_tasks.task_ingest_json_shop1": {"queue": "webscraper"},
    # AutoML 任务路由
    "automl.preprocessing_rapid": {"queue": "automl_preprocessing"},
    "automl.preprocessing_rapid_simple": {"queue": "automl_preprocessing"},
    "automl.cause_and_effect_testing": {"queue": "automl_cause_effect"},
    "automl.cause_and_effect_testing_simple": {"queue": "automl_cause_effect"},
    "automl.quantification_of_impact": {"queue": "automl_impact"},
    "automl.quantification_of_impact_simple": {"queue": "automl_impact"},
}

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                    'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable', ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells',
                               'tableProperties', 'tableCellProperties'],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h3', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h5', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},

            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_ANALYSIS = False

SIMPLEPRO_SECRET_KEY = os.getenv('SIMPLEPRO_SECRET_KEY', '')
SIMPLEPRO_MONIT_DISPLAY = True
SIMPLEPRO_INFO = True
SIMPLEPRO_FK_ASYNC_DATA = True

# SIMPLEUI_HOME_PAGE = "/admin-home"
SIMPLEUI_HOME_ICON = 'fa fa-user'

# SIMPLEUI_CONFIG = {
#     'system_keep': True,
#     'dynamic': False,
#     'menu_display': ['iPhone関連データ', ],
#     'menus':
#         [
#             {
#                 'name': 'iPhone関連データ',
#                 'icon': 'fa-solid fa-mobile-screen-button',
#                 'models': [{'name': '中古店価格推移(',
#                             'icon': 'fa-solid fa-chart-line',
#                             'url': '/AppleStockChecker/analysis-dashboard/',
#                             },
#                            {'name': '实时图表',
#                             'icon': 'fa-solid fa-store',
#                             'url': '/AppleStockChecker/statistical-data-summary/',
#                             },
#                            {'name': '中古店価格ボード',
#                             'icon': 'fa-solid fa-table-columns',
#                             'url': '/AppleStockChecker/price-matrix/',
#                             },
#                            {'name': 'iPhone公式在庫表',
#                             'icon': 'fa-solid fa-warehouse',
#                             'url': '/AppleStockChecker/price-matrix/',
#                             },
#                            {'name': '在庫',
#                             'icon': 'fa-solid fa-warehouse',
#                             'url': '/inbound-goods/',
#                             },

#                            {'name': '中古店価格メタデータ',
#                             'icon': 'fa-solid fa-database',
#                             'models': [{'name': 'iPhoneモデル',
#                                         'icon': 'fa-solid fa-mobile-button',
#                                         'url': '/admin/AppleStockChecker/iphone/',
#                                         },
#                                        {'name': '中古店',
#                                         'icon': 'fa-solid fa-shop',
#                                         'url': '/admin/AppleStockChecker/secondhandshop/'
#                                         },
#                                        {'name': '中古店価格記録',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/purchasingshoppricerecord/'
#                                         },
#                                        {'name': '价格整形记录',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/purchasingshoptimeanalysis/'
#                                         },

#                                        {'name': '基础统计featuresnapshot-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/featuresnapshot/'
#                                         },
#                                        {'name': '参数空间featurespec-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/featurespec/'
#                                         },

#                                        {'name': '统计模型modelartifact-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/modelartifact/'
#                                         },
#                                        {'name': '预测模型forecastsnapshot-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/forecastsnapshot/'
#                                         },
#                                        {'name': 'cohortbar-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/cohortbar/'
#                                         },

#                                        {'name': 'cohortmember-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/cohortmember/'
#                                         },
#                                        {'name': 'cohort-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/cohort/'
#                                         },
#                                        {'name': 'overallbar-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/overallbar/'
#                                         },
#                                        {'name': 'shopweightitem-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/shopweightitem/'
#                                         },
#                                        {'name': 'shopweightprofile-data',
#                                         'icon': 'fa-solid fa-money-check-dollar',
#                                         'url': '/admin/AppleStockChecker/shopweightprofile/'
#                                         },


#                                        ]
#                             },
#                            {'name': 'iPhone公式在庫メタデータ',
#                             'icon': 'fa-solid fa-file-contract',
#                             'models': [{'name': 'Apple公式ストア',
#                                         'icon': 'fa-solid fa-store',
#                                         'url': '/admin/AppleStockChecker/officialstore/',
#                                         },
#                                        {'name': 'iphone官方在库記録',
#                                         'icon': 'fa-solid fa-truck-ramp-box',
#                                         'url': '/admin/AppleStockChecker/inventoryrecord/'
#                                         },
#                                        ]
#                             },
#                            {'name': '临时页面',
#                             'icon': 'fa-solid fa-file-contract',
#                             'models': [
#                                 {'name': '価格推移(Model別)',
#                                  'icon': 'fa-solid fa-chart-line',
#                                  'url': '/AppleStockChecker/resale-trend-colors-merged/',
#                                  },
#                                 {'name': '间隔',
#                                  'icon': 'fa-solid fa-chart-line',
#                                  'url': '/admin/django_celery_beat/intervalschedule/',
#                                  },
#                                 {'name': '计划任务',
#                                  'icon': 'fa-solid fa-chart-line',
#                                  'url': '/admin/django_celery_beat/crontabschedule/',
#                                  },
#                                 {'name': '日程时间',
#                                  'icon': 'fa-solid fa-chart-line',
#                                  'url': '/admin/django_celery_beat/solarschedule/',
#                                  },
#                                 {'name': '定时',
#                                  'icon': 'fa-solid fa-chart-line',
#                                  'url': '/admin/django_celery_beat/clockedschedule/',
#                                  },

#                                 {'name': '周期性任务',
#                                  'icon': 'fa-solid fa-chart-line',
#                                  'url': '/admin/django_celery_beat/periodictask/',
#                                  },
#                                 {'name': '用户',
#                                  'icon': 'fa-solid fa-chart-line',
#                                  'url': '/admin/auth/user/',
#                                  },
#                                 {'name': '组',
#                                  'icon': 'fa-solid fa-chart-line',
#                                  'url': '/admin/auth/group/',
#                                  },

#                             ]
#                             },
#                            ]
#             },

#         ]}

# --- 本地开发：允许 Session 认证 + JWT；生产保持只有 JWT ---
if os.getenv("DJANGO_ENV", "dev") == "dev":
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework.authentication.SessionAuthentication",  # 浏览器登录态
            "rest_framework_simplejwt.authentication.JWTAuthentication",  # 保留 JWT
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    }
else:
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework_simplejwt.authentication.JWTAuthentication",
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    }


DJANGO_EASY_AUDIT_WATCH_MODEL_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_AUTH_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False
DJANGO_EASY_AUDIT_UNREGISTERED_URLS_DEFAULT = [r'^/static/',
                                               r'^/favicon.ico$',
                                               r'^/media/',
                                               r'^/__debug__/',
                                               r'^/ckeditor5/',
                                               ]

TIME_INPUT_FORMATS = "%H:%M"

SHOP_DISPLAY_ORDER = [
    "買取商店",
    "海峡通信",  # shop2　　　      ２
    "買取一丁目",  # shop3         ３
    "モバイルミックス",  # shop4    4
    "森森買取",  # shop5           ５
    "買取ルデヤ",  # shop6         ６
    "買取wiki",  # shop8          ７
    "買取ホムラ",  # shop7         ８
    "ドラゴンモバイル",  # shop10　　９
    "モバステ",  # shop11　         10
    "アキモバ",  # shop9           11
    "トゥインクル",  # shop12        12
    "家電市場",  # shop13           13
    "買取楽園",  # shop14           14
    "買取当番",  # shop15           15
    "携帯空間",  # shop16           16
    "ゲストモバイル",  # shop17      17
    "買取オク",  # shop18            18
    "毎日買取",  # shop20           20
]

FX_API_KEYS = {
    "alphavantage": os.getenv("FX_ALPHAVANTAGE_KEY", ""),
    "finnhub": os.getenv("FX_FINNHUB_KEY", ""),
    "twelvedata": os.getenv("FX_TWELVEDATA_KEY", ""),
}

TREND_MAX_LOOKBACK_DAYS = 90
TREND_DB_MAX_WORKERS = 6
TREND_CPU_MAX_WORKERS = 0  # 0/None=自动核数
TREND_DOWNSAMPLE_TARGET = 0  # 每条曲线最多点数（0=关闭）

LIST_ORDER = [
    "iphone-17-pro-max-256",
    "iphone-17-pro-max-512",
    "iphone-17-pro-max-1024",
    "iphone-17-pro-max-2048",
    "iphone-17-pro-256",
    "iphone-17-pro-512",
    "iphone-17-pro-1024",
    "iphone-Air-256",
    "iphone-Air-512",
    "iphone-Air-1024",
    "iphone-17-256",
    "iphone-17-512"
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(os.getenv("REDIS_HOST", "127.0.0.1"), int(os.getenv("REDIS_PORT", "6379")))]},
    }
}

ASGI_APPLICATION = "YamagotiProjects.asgi.application"
DATA_UPLOAD_MAX_MEMORY_SIZE=10 * 1024 * 1024

EXTERNAL_GOODS_API_URL = os.getenv("EXTERNAL_GOODS_API_URL", "http://localhost:8080")
EXTERNAL_GOODS_API_TOKEN = os.getenv("EXTERNAL_GOODS_API_TOKEN", "")
EXTERNAL_GOODS_CATEGORY_FILTER = os.getenv("EXTERNAL_GOODS_CATEGORY_FILTER", "iPhone")
# iPhone 官方发布价格（用于市场 log 溢价计算）
IPHONE_OFFICIAL_PRICES = {
    1: 129800,  # iPhone 17-256-ブラック
    2: 129800,  # iPhone 17-256-ホワイト
    3: 129800,  # iPhone 17-256-ミストブルー
    4: 129800,  # iPhone 17-256-ラベンダー
    5: 129800,  # iPhone 17-256-セージ
    6: 164800,  # iPhone 17-512-ブラック
    7: 164800,  # iPhone 17-512-ホワイト
    8: 164800,  # iPhone 17-512-ミストブルー
    9: 164800,  # iPhone 17-512-ラベンダー
    10: 164800,  # iPhone 17-512-セージ
    11: 179800,  # iPhone 17 Pro-256-シルバー
    12: 179800,  # iPhone 17 Pro-256-コズミックオレンジ
    13: 179800,  # iPhone 17 Pro-256-ディープブルー
    14: 214800,  # iPhone 17 Pro-512-シルバー
    15: 214800,  # iPhone 17 Pro-512-コズミックオレンジ
    16: 214800,  # iPhone 17 Pro-512-ディープブルー
    17: 249800,  # iPhone 17 Pro-1024-シルバー
    18: 249800,  # iPhone 17 Pro-1024-コズミックオレンジ
    19: 249800,  # iPhone 17 Pro-1024-ディープブルー
    20: 194800,  # iPhone 17 Pro Max-256-シルバー
    21: 194800,  # iPhone 17 Pro Max-256-コズミックオレンジ
    22: 194800,  # iPhone 17 Pro Max-256-ディープブルー
    23: 229800,  # iPhone 17 Pro Max-512-シルバー
    24: 229800,  # iPhone 17 Pro Max-512-コズミックオレンジ
    25: 229800,  # iPhone 17 Pro Max-512-ディープブルー
    26: 264800,  # iPhone 17 Pro Max-1024-シルバー
    27: 264800,  # iPhone 17 Pro Max-1024-コズミックオレンジ
    28: 264800,  # iPhone 17 Pro Max-1024-ディープブルー
    29: 329800,  # iPhone 17 Pro Max-2048-シルバー
    30: 329800,  # iPhone 17 Pro Max-2048-コズミックオレンジ
    31: 329800,  # iPhone 17 Pro Max-2048-ディープブルー
    32: 159800,  # iPhone Air-256-スペースブラック
    33: 159800,  # iPhone Air-256-クラウドホワイト
    34: 159800,  # iPhone Air-256-ライトゴールド
    35: 159800,  # iPhone Air-256-スカイブルー
    36: 194800,  # iPhone Air-512-スペースブラック
    37: 194800,  # iPhone Air-512-クラウドホワイト
    38: 194800,  # iPhone Air-512-ライトゴールド
    39: 194800,  # iPhone Air-512-スカイブルー
    40: 229800,  # iPhone Air-1024-スペースブラック
    41: 229800,  # iPhone Air-1024-クラウドホワイト
    42: 229800,  # iPhone Air-1024-ライトゴールド
    43: 229800,  # iPhone Air-1024-スカイブルー
}


# ============================================================================
# ClickHouse (GPU Pipeline 用)
# 参考: docs/REFACTOR_PLAN_V1.md §18
# ============================================================================
CLICKHOUSE_HOST     = os.getenv('CLICKHOUSE_HOST', 'localhost')
CLICKHOUSE_PORT     = int(os.getenv('CLICKHOUSE_PORT', '9000'))
CLICKHOUSE_DB       = os.getenv('CLICKHOUSE_DB', 'yamagoti')
CLICKHOUSE_USER     = os.getenv('CLICKHOUSE_USER', 'default')
CLICKHOUSE_PASSWORD = os.getenv('CLICKHOUSE_PASSWORD', '')

# Pipeline 默认参数
PIPELINE_DEVICE     = os.getenv('PIPELINE_DEVICE', 'cuda:0')
PIPELINE_BATCH_DAYS = int(os.getenv('PIPELINE_BATCH_DAYS', '30'))

# ============================================================================
# Logging Configuration
# ============================================================================
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

# 为 shop cleaners 创建专门的日志目录
SHOP_CLEANERS_LOG_DIR = LOG_DIR / "shop_cleaners"
SHOP_CLEANERS_LOG_DIR.mkdir(exist_ok=True)

class _DebugOnlyFilter(logging.Filter):
    """只允许 DEBUG 级别通过，过滤掉 INFO 及以上。"""
    def filter(self, record):
        return record.levelno == logging.DEBUG


class _DebugAndWarningFilter(logging.Filter):
    """允许 DEBUG 和 WARNING 级别通过，过滤掉 INFO/ERROR/CRITICAL。
    用于 shop17_file_json：DEBUG 记录详细处理过程，WARNING 记录 label 未匹配等异常。"""
    def filter(self, record):
        return record.levelno in (logging.DEBUG, logging.WARNING)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname:<7s} {asctime} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
            'timestamp': True,
        },
    },
    'filters': {
        'debug_only': {
            '()': _DebugOnlyFilter,
        },
        'debug_and_warning': {
            '()': _DebugAndWarningFilter,
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',  # 控制台只显示 INFO 及以上
        },
        'shop_cleaners_file_json': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(SHOP_CLEANERS_LOG_DIR / 'shop_cleaners.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 14,
            'encoding': 'utf-8',
            'formatter': 'json',
            'level': 'DEBUG',
            'filters': ['debug_and_warning'],  # DEBUG + WARNING 写入 JSON 文件，INFO+ 走 console → docker-logs
        },
    },
    'loggers': {
        'AppleStockChecker.tasks.timestamp_alignment_task': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'AppleStockChecker': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # 所有 shop cleaners 共用 logger（包级别）
        'AppleStockChecker.utils.external_ingest.shop_cleaners_split': {
            'handlers': ['console', 'shop_cleaners_file_json'],
            'level': os.getenv('SHOP_CLEANERS_LOG_LEVEL', 'DEBUG'),
            'propagate': False,
        },
        # 默认通用 logger
        'cleaner_tools': {
            'handlers': ['console', 'shop_cleaners_file_json'],
            'level': os.getenv('SHOP_CLEANERS_LOG_LEVEL', 'DEBUG'),
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# 动态为每个店铺生成独立的日志隔离配置
# 这里的 shop_code 对应 setup_color_cleaner(..., cleaner_name=CLEANER_NAME) 中的名字
for _shop_code in set(WEB_SCRAPER_SOURCE_MAP.values()):
    _handler_name = f'handler_{_shop_code}_file_json'
    
    # 1. 动态添加 Handler
    LOGGING['handlers'][_handler_name] = {
        'class': 'logging.handlers.TimedRotatingFileHandler',
        'filename': str(SHOP_CLEANERS_LOG_DIR / f'{_shop_code}.log'),
        'when': 'midnight',
        'interval': 1,
        'backupCount': 14,
        'encoding': 'utf-8',
        'formatter': 'json',
        'level': 'DEBUG',
        'filters': ['debug_and_warning'],
    }
    
    # 2. 动态添加特定的 Logger (覆盖 cleaner_tools.shopXX 和包路径命名)
    # cleaner_tools.shopXX 是 setup_color_cleaner 使用的
    LOGGING['loggers'][f'cleaner_tools.{_shop_code}'] = {
        'handlers': ['console', _handler_name],
        'level': os.getenv('SHOP_CLEANERS_LOG_LEVEL', 'DEBUG'),
        'propagate': False,
    }
    # 兼容某些 shop 内部使用 getLogger(__name__) 的情况
    LOGGING['loggers'][f'AppleStockChecker.utils.external_ingest.shop_cleaners_split.{_shop_code}_cleaner'] = {
        'handlers': ['console', _handler_name],
        'level': os.getenv('SHOP_CLEANERS_LOG_LEVEL', 'DEBUG'),
        'propagate': False,
    }

# ---- Elastic APM ----
ELASTIC_APM = {
    'SERVICE_NAME': 'yamagoti-projects',
    'SERVER_URL': 'http://host.docker.internal:8200',
    'ENVIRONMENT': os.getenv('DJANGO_ENV', 'dev'),
    'DEBUG': True,
    'DISABLE_SEND': False,
    'CAPTURE_BODY': 'all',
    'TRANSACTION_SAMPLE_RATE': 1.0,
    'SPAN_SAMPLE_RATE': 1.0,
}
