# Generated by Django 5.2.6 on 2025-09-27 06:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.CharField(blank=True, db_index=True, help_text='13位JAN码，如 4549995536515', max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', code='invalid_jan', message='JAN 必须是 13 位数字')], verbose_name='JAN')),
                ('part_number', models.CharField(help_text='Apple 部件号，如 MTLX3J/A', max_length=32, unique=True, verbose_name='唯一编码(Part Number)')),
                ('model_name', models.CharField(db_index=True, max_length=64, verbose_name='型号')),
                ('capacity_gb', models.PositiveSmallIntegerField(help_text='以 GB 为单位；如需 1TB = 1024GB', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4096)], verbose_name='容量(GB)')),
                ('color', models.CharField(db_index=True, max_length=32, verbose_name='颜色')),
                ('release_date', models.DateField(db_index=True, verbose_name='上市时间')),
            ],
            options={
                'verbose_name': 'iPhone 机型',
                'verbose_name_plural': 'iPhone 机型',
                'ordering': ['-release_date', 'model_name', 'capacity_gb'],
                'indexes': [models.Index(fields=['model_name', 'capacity_gb'], name='idx_model_cap'), models.Index(fields=['jan'], name='idx_iphone_jan')],
                'constraints': [models.UniqueConstraint(fields=('model_name', 'capacity_gb', 'color'), name='unique_iphone_variant')],
            },
        ),
        migrations.CreateModel(
            name='OfficialStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='商店名')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
            ],
            options={
                'verbose_name': '官方门店',
                'verbose_name_plural': '官方门店',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_store_name')],
            },
        ),
        migrations.CreateModel(
            name='SecondHandShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='店铺名称')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='网址')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
            ],
            options={
                'verbose_name': '二手店',
                'verbose_name_plural': '二手店',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_shs_name'), models.Index(fields=['address'], name='idx_shs_addr')],
                'constraints': [models.UniqueConstraint(fields=('name', 'address'), name='uniq_secondhandshop_name_addr')],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_stock', models.BooleanField(db_index=True, default=False, verbose_name='是否有库存')),
                ('estimated_arrival_earliest', models.DateTimeField(blank=True, null=True, verbose_name='配送到达最早时间')),
                ('estimated_arrival_latest', models.DateTimeField(blank=True, null=True, verbose_name='配送到达最晚时间')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='记录时间')),
                ('iphone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='AppleStockChecker.iphone', verbose_name='iPhone')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='AppleStockChecker.officialstore', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '库存记录',
                'verbose_name_plural': '库存记录',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['store', 'iphone', '-recorded_at'], name='idx_store_iphone_time'), models.Index(fields=['iphone', '-recorded_at'], name='idx_iphone_time'), models.Index(fields=['store', 'has_stock'], name='idx_store_stock')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estimated_arrival_earliest__isnull', True), ('estimated_arrival_latest__isnull', True), ('estimated_arrival_earliest__lte', models.F('estimated_arrival_latest')), _connector='OR'), name='chk_arrival_window_order')],
            },
        ),
        migrations.CreateModel(
            name='PurchasingShopPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='一次导入/任务的批次标识（uuid4）', null=True, verbose_name='批次ID')),
                ('price_new', models.PositiveIntegerField(verbose_name='新品卖取价格(円)')),
                ('price_grade_a', models.PositiveIntegerField(blank=True, null=True, verbose_name='A品卖取价格(円)')),
                ('price_grade_b', models.PositiveIntegerField(blank=True, null=True, verbose_name='B品卖取价格(円)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='记录时间')),
                ('iphone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_price_records', to='AppleStockChecker.iphone', verbose_name='iPhone')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_records', to='AppleStockChecker.secondhandshop', verbose_name='二手店')),
            ],
            options={
                'verbose_name': '二手店回收价格记录',
                'verbose_name_plural': '二手店回收价格记录',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['shop', 'iphone', '-recorded_at'], name='idx_pspr_shop_phone_time'), models.Index(fields=['iphone', '-recorded_at'], name='idx_pspr_phone_time'), models.Index(fields=['shop', '-recorded_at'], name='idx_pspr_shop_time')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'iphone', 'recorded_at'), name='uniq_shop_iphone_recorded_at')],
            },
        ),
    ]
