# Generated by Django 5.2.6 on 2025-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0003_alter_purchasingshoptimeanalysis_record_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Alignment_Time_Difference',
            field=models.IntegerField(db_column='alignment_time_difference', verbose_name='对齐时间差（s）'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Batch_ID',
            field=models.UUIDField(blank=True, db_column='batch_id', db_index=True, editable=False, help_text='一次导入/任务的批次标识（uuid4）', null=True, verbose_name='批次ID'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Job_ID',
            field=models.CharField(db_column='job_id', editable=False, max_length=255, verbose_name='Job_ID'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='New_Product_Price',
            field=models.PositiveIntegerField(db_column='new_product_price', verbose_name='新品卖取价格(円)'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Original_Record_Time_Zone',
            field=models.CharField(db_column='original_record_time_zone', max_length=10, verbose_name='原始记录时区'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Price_A',
            field=models.PositiveIntegerField(blank=True, db_column='price_a', null=True, verbose_name='A品卖取价格(円)'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Price_B',
            field=models.PositiveIntegerField(blank=True, db_column='price_b', null=True, verbose_name='B品卖取价格(円)'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Record_Time',
            field=models.DateTimeField(db_column='record_time', verbose_name='原始记录时间'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Timestamp_Time',
            field=models.DateTimeField(db_column='timestamp_time', db_index=True, verbose_name='时间戳时间'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Timestamp_Time_Zone',
            field=models.CharField(db_column='timestamp_time_zone', max_length=10, verbose_name='时间戳时区'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Update_Count',
            field=models.IntegerField(db_column='update_count', default=0, verbose_name='更新次数'),
        ),
        migrations.AlterField(
            model_name='purchasingshoptimeanalysis',
            name='Warehouse_Receipt_Time',
            field=models.DateTimeField(auto_now_add=True, db_column='warehouse_receipt_time', verbose_name='落库时间'),
        ),
    ]
