# Generated by Django 5.2.6 on 2025-11-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0004_alter_purchasingshoptimeanalysis_alignment_time_difference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=64)),
                ('version', models.CharField(db_index=True, max_length=32)),
                ('trained_at', models.DateTimeField()),
                ('params_blob', models.BinaryField()),
                ('metrics_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OverallBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True, unique=True)),
                ('mean', models.DecimalField(decimal_places=4, max_digits=12)),
                ('median', models.DecimalField(decimal_places=4, max_digits=12)),
                ('std', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('shop_count', models.IntegerField()),
                ('dispersion', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('scope', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField()),
                ('version', models.CharField(default='v1', max_length=16)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'name', 'bucket'], name='AppleStockC_scope_c153b5_idx')],
                'unique_together': {('bucket', 'scope', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('model_name', models.CharField(db_index=True, max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('horizon_min', models.IntegerField(default=1)),
                ('yhat', models.FloatField()),
                ('yhat_var', models.FloatField(null=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['bucket', 'model_name', 'version'], name='AppleStockC_bucket_8b81bb_idx')],
                'unique_together': {('bucket', 'model_name', 'version', 'horizon_min')},
            },
        ),
        migrations.CreateModel(
            name='CohortBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('mean', models.DecimalField(decimal_places=4, max_digits=12)),
                ('median', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('std', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('n_models', models.IntegerField()),
                ('shop_count_agg', models.IntegerField()),
                ('dispersion', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='AppleStockChecker.cohort')),
            ],
            options={
                'indexes': [models.Index(fields=['cohort', 'bucket'], name='AppleStockC_cohort__37267e_idx'), models.Index(fields=['bucket'], name='AppleStockC_bucket_3cdcc6_idx')],
                'unique_together': {('bucket', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='CohortMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='AppleStockChecker.cohort')),
                ('iphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppleStockChecker.iphone')),
            ],
            options={
                'unique_together': {('cohort', 'iphone')},
            },
        ),
    ]
