# Generated by Django 5.2.6 on 2025-11-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0006_psta_align_safe'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasingshoptimeanalysis',
            table='AppleStockChecker_purchasingshoptimeanalysis',
        ),
    ]
