# Generated by Django 5.2.6 on 2025-11-07 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0007_alter_purchasingshoptimeanalysis_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopWeightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopWeightProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='overallbar',
            name='iphone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='overall_bars', to='AppleStockChecker.iphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overallbar',
            name='bucket',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='overallbar',
            unique_together={('bucket', 'iphone')},
        ),
        migrations.AddIndex(
            model_name='overallbar',
            index=models.Index(fields=['iphone', 'bucket'], name='AppleStockC_iphone__5a48cf_idx'),
        ),
        migrations.AddIndex(
            model_name='overallbar',
            index=models.Index(fields=['bucket'], name='AppleStockC_bucket_dce830_idx'),
        ),
        migrations.AddField(
            model_name='shopweightitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppleStockChecker.secondhandshop'),
        ),
        migrations.AddField(
            model_name='shopweightitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AppleStockChecker.shopweightprofile'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='shop_weight_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppleStockChecker.shopweightprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='shopweightitem',
            unique_together={('profile', 'shop')},
        ),
    ]
