# Generated by Django 5.2.6 on 2025-11-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0008_shopweightitem_shopweightprofile_overallbar_iphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='display_index',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
