# Generated by Django 5.2.6 on 2025-11-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0011_shopweightitem_display_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('family', models.CharField(db_index=True, max_length=32)),
                ('base_name', models.CharField(db_index=True, default='mean', max_length=32)),
                ('params', models.JSONField(default=dict)),
                ('version', models.CharField(db_index=True, default='v1', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
