# Generated by Django 5.2.6 on 2026-02-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppleStockChecker', '0012_featurespec'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionLog',
            fields=[
                ('batch_id', models.UUIDField(editable=False, help_text='批次唯一标识（uuid4）', primary_key=True, serialize=False, verbose_name='批次ID')),
                ('task_type', models.CharField(choices=[('xlsx', 'XLSX/CSV 文件导入'), ('webscraper', 'WebScraper 数据拉取'), ('json_shop1', 'Shop1 JSON 直接摄入')], db_index=True, max_length=20, verbose_name='任务类型')),
                ('source_name', models.CharField(db_index=True, help_text='如 shop1, shop2, shop5_1 等', max_length=64, verbose_name='数据源名称')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Celery 接收任务ID')),
                ('cleaning_task_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Celery 清洗任务ID')),
                ('cleaning_queue', models.CharField(blank=True, default='', help_text='实际路由到的队列，如 shop_shop1', max_length=64, verbose_name='清洗队列名')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='任务创建时间')),
                ('received_at', models.DateTimeField(blank=True, help_text='解析/拉取成功的时间', null=True, verbose_name='数据接收完成时间')),
                ('cleaning_started_at', models.DateTimeField(blank=True, null=True, verbose_name='清洗开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='清洗完成时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('receiving', '数据接收中'), ('cleaning', '清洗中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('input_filename', models.CharField(blank=True, default='', help_text='XLSX/CSV 文件名', max_length=255, verbose_name='输入文件名')),
                ('input_job_id', models.CharField(blank=True, default='', help_text='WebScraper 任务 ID', max_length=64, verbose_name='WebScraper Job ID')),
                ('rows_received', models.PositiveIntegerField(blank=True, help_text='原始数据行数', null=True, verbose_name='接收行数')),
                ('rows_after_cleaning', models.PositiveIntegerField(blank=True, null=True, verbose_name='清洗后行数')),
                ('rows_inserted', models.PositiveIntegerField(blank=True, null=True, verbose_name='新插入行数')),
                ('rows_updated', models.PositiveIntegerField(blank=True, help_text='upsert 模式下更新的行数', null=True, verbose_name='更新行数')),
                ('rows_skipped', models.PositiveIntegerField(blank=True, help_text='去重跳过的行数', null=True, verbose_name='跳过行数')),
                ('rows_unmatched', models.PositiveIntegerField(blank=True, help_text='未找到对应 iPhone 的行数', null=True, verbose_name='未匹配行数')),
                ('dry_run', models.BooleanField(default=False, verbose_name='仅预览')),
                ('dedupe', models.BooleanField(default=True, verbose_name='启用去重')),
                ('upsert', models.BooleanField(default=False, verbose_name='启用更新')),
            ],
            options={
                'verbose_name': '数据摄入日志',
                'verbose_name_plural': '数据摄入日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dataingestionlog',
            index=models.Index(fields=['task_type', '-created_at'], name='idx_dil_type_time'),
        ),
        migrations.AddIndex(
            model_name='dataingestionlog',
            index=models.Index(fields=['source_name', '-created_at'], name='idx_dil_source_time'),
        ),
        migrations.AddIndex(
            model_name='dataingestionlog',
            index=models.Index(fields=['status', '-created_at'], name='idx_dil_status_time'),
        ),
    ]
