# Generated by Django 5.2 on 2026-01-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregation', '0008_merge_20260109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcreditcard',
            name='alternative_name',
            field=models.CharField(blank=True, help_text='Human-friendly alternative name for easy management', max_length=100, null=True, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='historicaldebitcard',
            name='alternative_name',
            field=models.CharField(blank=True, help_text='Human-friendly alternative name for easy management', max_length=100, null=True, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='historicalgiftcard',
            name='alternative_name',
            field=models.CharField(blank=True, help_text='Human-friendly alternative name for easy management', max_length=100, null=True, verbose_name='别名'),
        ),
    ]
