# Generated by Django 5.2 on 2026-01-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_aggregation",
            "0009_alter_historicalcreditcard_alternative_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinventory",
            name="imei",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="International Mobile Equipment Identity (up to 17 characters)",
                max_length=17,
                null=True,
                verbose_name="IMEI",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="imei",
            field=models.CharField(
                blank=True,
                help_text="International Mobile Equipment Identity (up to 17 characters)",
                max_length=17,
                null=True,
                unique=True,
                verbose_name="IMEI",
            ),
        ),
    ]
