# Generated by Django 5.2 on 2026-01-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_aggregation", "0010_historicalinventory_imei_inventory_imei"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinventory",
            name="batch_level_1",
            field=models.CharField(
                blank=True,
                help_text="First level batch identifier for inventory management",
                max_length=255,
                null=True,
                verbose_name="Batch Level 1",
            ),
        ),
        migrations.AddField(
            model_name="historicalinventory",
            name="batch_level_2",
            field=models.CharField(
                blank=True,
                help_text="Second level batch identifier for inventory management",
                max_length=255,
                null=True,
                verbose_name="Batch Level 2",
            ),
        ),
        migrations.AddField(
            model_name="historicalinventory",
            name="batch_level_3",
            field=models.CharField(
                blank=True,
                help_text="Third level batch identifier for inventory management",
                max_length=255,
                null=True,
                verbose_name="Batch Level 3",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="batch_level_1",
            field=models.CharField(
                blank=True,
                help_text="First level batch identifier for inventory management",
                max_length=255,
                null=True,
                verbose_name="Batch Level 1",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="batch_level_2",
            field=models.CharField(
                blank=True,
                help_text="Second level batch identifier for inventory management",
                max_length=255,
                null=True,
                verbose_name="Batch Level 2",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="batch_level_3",
            field=models.CharField(
                blank=True,
                help_text="Third level batch identifier for inventory management",
                max_length=255,
                null=True,
                verbose_name="Batch Level 3",
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["batch_level_1"], name="inventory_batch_l_785e42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["batch_level_2"], name="inventory_batch_l_680e1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["batch_level_3"], name="inventory_batch_l_1fef5b_idx"
            ),
        ),
    ]
