# Generated by Django 5.2 on 2026-01-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_aggregation", "0011_historicalinventory_batch_level_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpurchasing",
            name="batch_encoding",
            field=models.CharField(
                blank=True,
                help_text="Batch encoding for grouping purchases",
                max_length=50,
                verbose_name="批次编码",
            ),
        ),
        migrations.AddField(
            model_name="historicalpurchasing",
            name="batch_level_1",
            field=models.CharField(
                blank=True,
                help_text="Batch level 1 identifier",
                max_length=50,
                verbose_name="批次层级1",
            ),
        ),
        migrations.AddField(
            model_name="historicalpurchasing",
            name="batch_level_2",
            field=models.CharField(
                blank=True,
                help_text="Batch level 2 identifier",
                max_length=50,
                verbose_name="批次层级2",
            ),
        ),
        migrations.AddField(
            model_name="historicalpurchasing",
            name="batch_level_3",
            field=models.CharField(
                blank=True,
                help_text="Batch level 3 identifier",
                max_length=50,
                verbose_name="批次层级3",
            ),
        ),
        migrations.AddField(
            model_name="purchasing",
            name="batch_encoding",
            field=models.CharField(
                blank=True,
                help_text="Batch encoding for grouping purchases",
                max_length=50,
                verbose_name="批次编码",
            ),
        ),
        migrations.AddField(
            model_name="purchasing",
            name="batch_level_1",
            field=models.CharField(
                blank=True,
                help_text="Batch level 1 identifier",
                max_length=50,
                verbose_name="批次层级1",
            ),
        ),
        migrations.AddField(
            model_name="purchasing",
            name="batch_level_2",
            field=models.CharField(
                blank=True,
                help_text="Batch level 2 identifier",
                max_length=50,
                verbose_name="批次层级2",
            ),
        ),
        migrations.AddField(
            model_name="purchasing",
            name="batch_level_3",
            field=models.CharField(
                blank=True,
                help_text="Batch level 3 identifier",
                max_length=50,
                verbose_name="批次层级3",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasing",
            index=models.Index(
                fields=["batch_encoding"], name="purchasing_batch_e_8a1b2c_idx"
            ),
        ),
    ]
