# Generated by Django 5.2 on 2026-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregation', '0023_alter_ecsite_uuid_alter_historicalecsite_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('analysis', '邮件分析'), ('initial_order', '初始确认'), ('notification', '通知生成'), ('send', '邮件发送')], max_length=30)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '进行中'), ('success', '成功'), ('error', '异常')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'email_processing_logs',
                'indexes': [models.Index(fields=['stage', 'created_at'], name='email_proce_stage_624c1d_idx')],
            },
        ),
    ]
