# Generated by Django 5.0 on 2026-01-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0007_alter_historicaltrackingjob_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrackingjob',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('redirected', 'Redirected'),
                ],
                db_index=True,
                default='pending',
                help_text='Task status',
                max_length=20,
                verbose_name='Status'
            ),
        ),
        migrations.AlterField(
            model_name='trackingjob',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('redirected', 'Redirected'),
                ],
                db_index=True,
                default='pending',
                help_text='Task status',
                max_length=20,
                verbose_name='Status'
            ),
        ),
    ]
