# Generated by Django 5.0 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0008_add_redirected_status_to_trackingjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingbatch',
            name='writeback_triggered',
            field=models.BooleanField(
                default=False,
                help_text='是否已触发批量回写任务',
                verbose_name='Writeback Triggered'
            ),
        ),
        migrations.AddField(
            model_name='trackingbatch',
            name='writeback_completed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='批量回写完成时间',
                null=True,
                verbose_name='Writeback Completed At'
            ),
        ),
        migrations.AddField(
            model_name='historicaltrackingbatch',
            name='writeback_triggered',
            field=models.BooleanField(
                default=False,
                help_text='是否已触发批量回写任务',
                verbose_name='Writeback Triggered'
            ),
        ),
        migrations.AddField(
            model_name='historicaltrackingbatch',
            name='writeback_completed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='批量回写完成时间',
                null=True,
                verbose_name='Writeback Completed At'
            ),
        ),
    ]
