# Generated by Django 5.0 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0009_add_writeback_fields_to_trackingbatch'),
    ]

    operations = [
        # Add writeback_data to TrackingJob
        migrations.AddField(
            model_name='trackingjob',
            name='writeback_data',
            field=models.TextField(
                blank=True,
                verbose_name='Writeback Data',
                help_text='提取的回写数据（用｜｜｜分隔）'
            ),
        ),
        # Add writeback_data to HistoricalTrackingJob
        migrations.AddField(
            model_name='historicaltrackingjob',
            name='writeback_data',
            field=models.TextField(
                blank=True,
                verbose_name='Writeback Data',
                help_text='提取的回写数据（用｜｜｜分隔）'
            ),
        ),
    ]
