# Generated by Django 5.2 on 2025-12-31 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Source Name')),
                ('source_type', models.CharField(choices=[('api', 'API'), ('database', 'Database'), ('file', 'File'), ('websocket', 'WebSocket'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20)),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('fetch_interval', models.IntegerField(default=3600, help_text='Fetch interval in seconds')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'data_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcquisitionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Celery Task ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Task Result')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('records_count', models.IntegerField(default=0, verbose_name='Records Acquired')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='data_acquisition.datasource')),
            ],
            options={
                'verbose_name': 'Acquisition Task',
                'verbose_name_plural': 'Acquisition Tasks',
                'db_table': 'acquisition_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextcloudSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Purchasing', 'Purchasing'), ('OfficialAccount', 'OfficialAccount'), ('GiftCard', 'GiftCard'), ('DebitCard', 'DebitCard'), ('CreditCard', 'CreditCard'), ('TemporaryChannel', 'TemporaryChannel')], help_text='Django model being synced', max_length=50, verbose_name='Model Name')),
                ('file_path', models.CharField(help_text='Nextcloud file path (e.g., /Data/Purchasing_abc123.xlsx)', max_length=500, unique=True, verbose_name='File Path')),
                ('last_etag', models.CharField(blank=True, help_text='ETag from last successful sync (for deduplication)', max_length=255, verbose_name='Last ETag')),
                ('last_modified', models.DateTimeField(blank=True, help_text='File last modified timestamp from WebDAV', null=True, verbose_name='Last Modified')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful sync', null=True, verbose_name='Last Synced At')),
                ('last_event_user', models.CharField(blank=True, help_text='Nextcloud user who triggered last event', max_length=255, verbose_name='Last Event User')),
                ('total_syncs', models.IntegerField(default=0, help_text='Total number of successful syncs', verbose_name='Total Syncs')),
                ('total_conflicts', models.IntegerField(default=0, help_text='Total number of conflicts detected', verbose_name='Total Conflicts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nextcloud Sync State',
                'verbose_name_plural': 'Nextcloud Sync States',
                'db_table': 'nextcloud_sync_states',
                'ordering': ['-last_synced_at'],
                'indexes': [models.Index(fields=['model_name'], name='nextcloud_s_model_n_90dd0e_idx'), models.Index(fields=['file_path'], name='nextcloud_s_file_pa_21c801_idx'), models.Index(fields=['last_etag'], name='nextcloud_s_last_et_8c5eee_idx'), models.Index(fields=['-last_synced_at'], name='nextcloud_s_last_sy_daf8dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcquiredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(verbose_name='Raw Data')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('data_hash', models.CharField(blank=True, max_length=64, verbose_name='Data Hash')),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired_data', to='data_acquisition.datasource')),
            ],
            options={
                'verbose_name': 'Acquired Data',
                'verbose_name_plural': 'Acquired Data',
                'db_table': 'acquired_data',
                'ordering': ['-acquired_at'],
                'indexes': [models.Index(fields=['-acquired_at'], name='acquired_da_acquire_2c112a_idx'), models.Index(fields=['source', '-acquired_at'], name='acquired_da_source__3fa19f_idx'), models.Index(fields=['data_hash'], name='acquired_da_data_ha_d0b67f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('version_mismatch', 'Version Mismatch'), ('concurrent_edit', 'Concurrent Edit'), ('validation_error', 'Validation Error')], default='version_mismatch', max_length=30, verbose_name='Conflict Type')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model Name')),
                ('record_id', models.IntegerField(blank=True, help_text='Primary key of conflicting record', null=True, verbose_name='Record ID')),
                ('excel_version', models.CharField(help_text='Version from Excel file', max_length=100, verbose_name='Excel Version')),
                ('db_version', models.CharField(help_text='Version from database', max_length=100, verbose_name='DB Version')),
                ('excel_data', models.JSONField(help_text='Data from Excel row', verbose_name='Excel Data')),
                ('db_data', models.JSONField(blank=True, help_text='Current data in database', null=True, verbose_name='DB Data')),
                ('status', models.CharField(choices=[('pending', 'Pending Resolution'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20, verbose_name='Status')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolved_by', models.CharField(blank=True, max_length=255, verbose_name='Resolved By')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='data_acquisition.nextcloudsyncstate', verbose_name='Sync State')),
            ],
            options={
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
                'db_table': 'sync_conflicts',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status'], name='sync_confli_status_32316a_idx'), models.Index(fields=['model_name', 'record_id'], name='sync_confli_model_n_6328a6_idx'), models.Index(fields=['-detected_at'], name='sync_confli_detecte_1bc8ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('webhook_received', 'Webhook Received'), ('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_deleted', 'Record Deleted'), ('conflict_detected', 'Conflict Detected'), ('excel_writeback', 'Excel Writeback'), ('writeback_skipped', 'Writeback Skipped')], max_length=30, verbose_name='Operation Type')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery Task ID')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='File Path')),
                ('etag', models.CharField(blank=True, max_length=255, verbose_name='ETag')),
                ('message', models.TextField(help_text='Log message', verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details (JSON)', verbose_name='Details')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_acquisition.nextcloudsyncstate', verbose_name='Sync State')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation_type'], name='sync_logs_operati_20e178_idx'), models.Index(fields=['success'], name='sync_logs_success_f13c88_idx'), models.Index(fields=['-created_at'], name='sync_logs_created_a9c4e8_idx'), models.Index(fields=['celery_task_id'], name='sync_logs_celery__b90b6c_idx')],
            },
        ),
    ]
