# Generated by Django 5.2 on 2026-01-09 07:11
# Modified to handle existing historical tables gracefully

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def create_historical_tables_if_not_exist(apps, schema_editor):
    """
    Create historical tables only if they don't already exist.
    This prevents "relation already exists" errors.
    """
    from django.db import connection

    # Check if tables already exist
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT tablename FROM pg_tables
            WHERE schemaname = 'public'
            AND tablename LIKE 'data_acquisition_historical%'
            AND tablename NOT IN ('data_acquisition_historicalsynclog', 'data_acquisition_historicaltrackingbatch', 'data_acquisition_historicaltrackingjob');
        """)
        existing_tables = [row[0] for row in cursor.fetchall()]

    if existing_tables:
        print(f"\nINFO: The following historical tables already exist: {', '.join(existing_tables)}")
        print("INFO: Skipping table creation, only updating Django migration state.\n")
    else:
        print("\nINFO: Creating historical tables for data_acquisition models.\n")


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0005_alter_synclog_operation_type_for_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, run a check to inform about existing tables
        migrations.RunPython(create_historical_tables_if_not_exist, reverse_code=migrations.RunPython.noop),

        # Use SeparateDatabaseAndState to handle existing tables gracefully
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # State operations: Tell Django about these models
                migrations.CreateModel(
                    name='HistoricalAcquiredData',
                    fields=[
                        ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                        ('change_source', models.CharField(choices=[('admin', 'Admin 管理后台'), ('api', 'REST API'), ('celery', 'Celery 异步任务'), ('sync', 'Nextcloud 同步'), ('shell', 'Django Shell/脚本'), ('onlyoffice_import', 'OnlyOffice 导入'), ('unknown', '未知来源')], default='unknown', help_text='Source of the modification', max_length=20, verbose_name='修改来源')),
                        ('raw_data', models.JSONField(verbose_name='Raw Data')),
                        ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                        ('data_hash', models.CharField(blank=True, max_length=64, verbose_name='Data Hash')),
                        ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('created_at', models.DateTimeField(blank=True, editable=False)),
                        ('history_id', models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField(db_index=True)),
                        ('history_change_reason', models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                    ],
                    options={
                        'verbose_name': 'historical Acquired Data',
                        'verbose_name_plural': 'historical Acquired Data',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': ('history_date', 'history_id'),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name='HistoricalAcquisitionTask',
                    fields=[
                        ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                        ('change_source', models.CharField(choices=[('admin', 'Admin 管理后台'), ('api', 'REST API'), ('celery', 'Celery 异步任务'), ('sync', 'Nextcloud 同步'), ('shell', 'Django Shell/脚本'), ('onlyoffice_import', 'OnlyOffice 导入'), ('unknown', '未知来源')], default='unknown', help_text='Source of the modification', max_length=20, verbose_name='修改来源')),
                        ('task_id', models.CharField(db_index=True, max_length=255, verbose_name='Celery Task ID')),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                        ('result', models.JSONField(blank=True, null=True, verbose_name='Task Result')),
                        ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                        ('records_count', models.IntegerField(default=0, verbose_name='Records Acquired')),
                        ('started_at', models.DateTimeField(blank=True, null=True)),
                        ('completed_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, editable=False)),
                        ('history_id', models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField(db_index=True)),
                        ('history_change_reason', models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                    ],
                    options={
                        'verbose_name': 'historical Acquisition Task',
                        'verbose_name_plural': 'historical Acquisition Tasks',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': ('history_date', 'history_id'),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name='HistoricalDataSource',
                    fields=[
                        ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                        ('change_source', models.CharField(choices=[('admin', 'Admin 管理后台'), ('api', 'REST API'), ('celery', 'Celery 异步任务'), ('sync', 'Nextcloud 同步'), ('shell', 'Django Shell/脚本'), ('onlyoffice_import', 'OnlyOffice 导入'), ('unknown', '未知来源')], default='unknown', help_text='Source of the modification', max_length=20, verbose_name='修改来源')),
                        ('name', models.CharField(db_index=True, max_length=255, verbose_name='Source Name')),
                        ('source_type', models.CharField(choices=[('api', 'API'), ('database', 'Database'), ('file', 'File'), ('websocket', 'WebSocket'), ('other', 'Other')], max_length=20)),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20)),
                        ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                        ('fetch_interval', models.IntegerField(default=3600, help_text='Fetch interval in seconds')),
                        ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, editable=False)),
                        ('updated_at', models.DateTimeField(blank=True, editable=False)),
                        ('history_id', models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField(db_index=True)),
                        ('history_change_reason', models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                    ],
                    options={
                        'verbose_name': 'historical Data Source',
                        'verbose_name_plural': 'historical Data Sources',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': ('history_date', 'history_id'),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name='HistoricalNextcloudSyncState',
                    fields=[
                        ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                        ('change_source', models.CharField(choices=[('admin', 'Admin 管理后台'), ('api', 'REST API'), ('celery', 'Celery 异步任务'), ('sync', 'Nextcloud 同步'), ('shell', 'Django Shell/脚本'), ('onlyoffice_import', 'OnlyOffice 导入'), ('unknown', '未知来源')], default='unknown', help_text='Source of the modification', max_length=20, verbose_name='修改来源')),
                        ('model_name', models.CharField(choices=[('Purchasing', 'Purchasing'), ('OfficialAccount', 'OfficialAccount'), ('GiftCard', 'GiftCard'), ('DebitCard', 'DebitCard'), ('CreditCard', 'CreditCard'), ('TemporaryChannel', 'TemporaryChannel')], help_text='Django model being synced', max_length=50, verbose_name='Model Name')),
                        ('file_path', models.CharField(db_index=True, help_text='Nextcloud file path (e.g., /Data/Purchasing_abc123.xlsx)', max_length=500, verbose_name='File Path')),
                        ('last_etag', models.CharField(blank=True, help_text='ETag from last successful sync (for deduplication)', max_length=255, verbose_name='Last ETag')),
                        ('last_modified', models.DateTimeField(blank=True, help_text='File last modified timestamp from WebDAV', null=True, verbose_name='Last Modified')),
                        ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful sync', null=True, verbose_name='Last Synced At')),
                        ('last_event_user', models.CharField(blank=True, help_text='Nextcloud user who triggered last event', max_length=255, verbose_name='Last Event User')),
                        ('total_syncs', models.IntegerField(default=0, help_text='Total number of successful syncs', verbose_name='Total Syncs')),
                        ('total_conflicts', models.IntegerField(default=0, help_text='Total number of conflicts detected', verbose_name='Total Conflicts')),
                        ('created_at', models.DateTimeField(blank=True, editable=False)),
                        ('updated_at', models.DateTimeField(blank=True, editable=False)),
                        ('history_id', models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField(db_index=True)),
                        ('history_change_reason', models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                    ],
                    options={
                        'verbose_name': 'historical Nextcloud Sync State',
                        'verbose_name_plural': 'historical Nextcloud Sync States',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': ('history_date', 'history_id'),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name='HistoricalSyncConflict',
                    fields=[
                        ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                        ('change_source', models.CharField(choices=[('admin', 'Admin 管理后台'), ('api', 'REST API'), ('celery', 'Celery 异步任务'), ('sync', 'Nextcloud 同步'), ('shell', 'Django Shell/脚本'), ('onlyoffice_import', 'OnlyOffice 导入'), ('unknown', '未知来源')], default='unknown', help_text='Source of the modification', max_length=20, verbose_name='修改来源')),
                        ('conflict_type', models.CharField(choices=[('version_mismatch', 'Version Mismatch'), ('concurrent_edit', 'Concurrent Edit'), ('validation_error', 'Validation Error')], default='version_mismatch', max_length=30, verbose_name='Conflict Type')),
                        ('model_name', models.CharField(max_length=50, verbose_name='Model Name')),
                        ('record_id', models.IntegerField(blank=True, help_text='Primary key of conflicting record', null=True, verbose_name='Record ID')),
                        ('excel_version', models.CharField(help_text='Version from Excel file', max_length=100, verbose_name='Excel Version')),
                        ('db_version', models.CharField(help_text='Version from database', max_length=100, verbose_name='DB Version')),
                        ('excel_data', models.JSONField(help_text='Data from Excel row', verbose_name='Excel Data')),
                        ('db_data', models.JSONField(blank=True, help_text='Current data in database', null=True, verbose_name='DB Data')),
                        ('status', models.CharField(choices=[('pending', 'Pending Resolution'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20, verbose_name='Status')),
                        ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                        ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                        ('resolved_by', models.CharField(blank=True, max_length=255, verbose_name='Resolved By')),
                        ('detected_at', models.DateTimeField(blank=True, editable=False)),
                        ('updated_at', models.DateTimeField(blank=True, editable=False)),
                        ('history_id', models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField(db_index=True)),
                        ('history_change_reason', models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                    ],
                    options={
                        'verbose_name': 'historical Sync Conflict',
                        'verbose_name_plural': 'historical Sync Conflicts',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': ('history_date', 'history_id'),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.RenameIndex(
                    model_name='trackingbatch',
                    new_name='acquisition_task_na_33c563_idx',
                    old_name='acq_track_batch_task_status_idx',
                ),
                migrations.RenameIndex(
                    model_name='trackingbatch',
                    new_name='acquisition_status_cd7b2f_idx',
                    old_name='acq_track_batch_status_idx',
                ),
                migrations.RenameIndex(
                    model_name='trackingjob',
                    new_name='acquisition_batch_i_93ce0a_idx',
                    old_name='acq_track_job_batch_status_idx',
                ),
                migrations.RenameIndex(
                    model_name='trackingjob',
                    new_name='acquisition_custom__cdccc7_idx',
                    old_name='acq_track_job_custom_id_idx',
                ),
                migrations.AddField(
                    model_name='historicalacquireddata',
                    name='history_user',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='historicalacquireddata',
                    name='source',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_acquisition.datasource'),
                ),
                migrations.AddField(
                    model_name='historicalacquisitiontask',
                    name='history_user',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='historicalacquisitiontask',
                    name='source',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_acquisition.datasource'),
                ),
                migrations.AddField(
                    model_name='historicaldatasource',
                    name='history_user',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='historicalnextcloudsyncstate',
                    name='history_user',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='historicalsyncconflict',
                    name='history_user',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='historicalsyncconflict',
                    name='sync_state',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_acquisition.nextcloudsyncstate', verbose_name='Sync State'),
                ),
            ],
            database_operations=[
                # Database operations: Create tables only if they don't exist
                migrations.RunSQL(
                    """
                    -- This SQL will be executed but won't fail if tables already exist
                    -- because we're using CREATE TABLE IF NOT EXISTS pattern
                    DO $$
                    BEGIN
                        -- The actual table creation is handled by Django's model system
                        -- This is just a placeholder to prevent errors
                        RAISE NOTICE 'Checking and creating historical tables if needed...';
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
