# Generated by Django 5.0 on 2026-01-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0006_historicalacquireddata_historicalacquisitiontask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrackingjob',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, help_text='WebScraper 返回的 job_id（如果 API 返回了）', max_length=100, null=True, verbose_name='WebScraper Job ID'),
        ),
        migrations.AlterField(
            model_name='trackingjob',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, help_text='WebScraper 返回的 job_id（如果 API 返回了）', max_length=100, null=True, unique=True, verbose_name='WebScraper Job ID'),
        ),
    ]
