# Generated by Django 5.2 on 2026-01-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0010_add_writeback_data_to_trackingjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsynclog',
            name='operation_type',
            field=models.CharField(choices=[('webhook_received', 'Webhook Received'), ('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_deleted', 'Record Deleted'), ('conflict_detected', 'Conflict Detected'), ('excel_writeback', 'Excel Writeback'), ('writeback_skipped', 'Writeback Skipped'), ('onlyoffice_callback', 'OnlyOffice Callback'), ('onlyoffice_document_processed', 'OnlyOffice Document Processed'), ('onlyoffice_process_failed', 'OnlyOffice Process Failed'), ('onlyoffice_import_skipped', 'OnlyOffice Import Skipped'), ('onlyoffice_import_completed', 'OnlyOffice Import Completed'), ('onlyoffice_missing_url', 'OnlyOffice Missing URL'), ('nextcloud_forward_failed', 'Nextcloud Forward Failed'), ('official_website_redirect_to_yamato_tracking_triggered', 'OWRYT Tracking Triggered'), ('official_website_redirect_to_yamato_tracking_completed', 'OWRYT Tracking Completed'), ('redirect_to_japan_post_tracking_triggered', 'Redirect to Japan Post Tracking Triggered'), ('redirect_to_japan_post_tracking_completed', 'Redirect to Japan Post Tracking Completed'), ('official_website_tracking_triggered', 'Official Website Tracking Triggered'), ('official_website_tracking_completed', 'Official Website Tracking Completed'), ('yamato_tracking_only_triggered', 'Yamato Tracking Only Triggered'), ('yamato_tracking_only_completed', 'Yamato Tracking Only Completed'), ('japan_post_tracking_only_triggered', 'Japan Post Tracking Only Triggered'), ('japan_post_tracking_only_completed', 'Japan Post Tracking Only Completed')], max_length=60, verbose_name='Operation Type'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('redirected', 'Redirected')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='operation_type',
            field=models.CharField(choices=[('webhook_received', 'Webhook Received'), ('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_deleted', 'Record Deleted'), ('conflict_detected', 'Conflict Detected'), ('excel_writeback', 'Excel Writeback'), ('writeback_skipped', 'Writeback Skipped'), ('onlyoffice_callback', 'OnlyOffice Callback'), ('onlyoffice_document_processed', 'OnlyOffice Document Processed'), ('onlyoffice_process_failed', 'OnlyOffice Process Failed'), ('onlyoffice_import_skipped', 'OnlyOffice Import Skipped'), ('onlyoffice_import_completed', 'OnlyOffice Import Completed'), ('onlyoffice_missing_url', 'OnlyOffice Missing URL'), ('nextcloud_forward_failed', 'Nextcloud Forward Failed'), ('official_website_redirect_to_yamato_tracking_triggered', 'OWRYT Tracking Triggered'), ('official_website_redirect_to_yamato_tracking_completed', 'OWRYT Tracking Completed'), ('redirect_to_japan_post_tracking_triggered', 'Redirect to Japan Post Tracking Triggered'), ('redirect_to_japan_post_tracking_completed', 'Redirect to Japan Post Tracking Completed'), ('official_website_tracking_triggered', 'Official Website Tracking Triggered'), ('official_website_tracking_completed', 'Official Website Tracking Completed'), ('yamato_tracking_only_triggered', 'Yamato Tracking Only Triggered'), ('yamato_tracking_only_completed', 'Yamato Tracking Only Completed'), ('japan_post_tracking_only_triggered', 'Japan Post Tracking Only Triggered'), ('japan_post_tracking_only_completed', 'Japan Post Tracking Only Completed')], max_length=60, verbose_name='Operation Type'),
        ),
        migrations.AlterField(
            model_name='trackingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('redirected', 'Redirected')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
