# Generated by Django 5.2 on 2026-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0011_alter_historicalsynclog_operation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrackingbatch',
            name='source_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('db', 'DB')], db_index=True, default='excel', help_text='数据来源类型：excel（文件驱动）或 db（数据库驱动）', max_length=10, verbose_name='Source Type'),
        ),
        migrations.AddField(
            model_name='trackingbatch',
            name='source_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('db', 'DB')], db_index=True, default='excel', help_text='数据来源类型：excel（文件驱动）或 db（数据库驱动）', max_length=10, verbose_name='Source Type'),
        ),
    ]
